Registrar/Models/Course.cs
using System.Collections.Generic;

namespace Registrar.Models
{
  public class Course
  {
    public int CourseId { get; set; }
    public string CourseName { get; set; }
    public string CourseNumber { get; set; }
    public List<StudentCourse> JoinEntities { get; }
  }
}

Registrar/Models/RegistrarContext.cs
using Microsoft.EntityFrameworkCore;

namespace Registrar.Models
{
  public class RegistrarContext : DbContext
  {
    public DbSet<Course> Courses { get; set;}
    public DbSet<Student> Students { get; set;}
    public DbSet<StudentCourse> StudentCourses { get; set; }

    public RegistrarContext(DbContextOptions options) : base(options) { }
  }
}

Registrar/Models/Student.cs
using System.Collections.Generic;

namespace Registrar.Models
{
  public class Student
  {
    public int StudentId { get; set; }
    public string StudentName { get; set; }
    public string DateOfEnrollment { get; set; }
    public List<StudentCourse> JoinEntities { get; }
  }
}

Registrar/Models/StudentCourse.cs
namespace Registrar.Models
{
  public class StudentCourse
  {
    public int StudentCourseId { get; set;}
    public int StudentId { get; set; }
    public Student Student { get; set; }
    public int CourseId { get; set; }
    public Course Course { get; set; }
  }
}

Registrar/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Registrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly RegistrarContext _db;

    public CoursesController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index() 
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Course thisCourse = _db.Courses
      .Include(course => course.JoinEntities)
      .ThenInclude(join => join.Student)
      .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Edit (int id)
    {
      Course thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course course)
    {
      _db.Courses.Update(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Course thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Course thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddStudent(int id)
    {
      Course thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
      ViewBag.StudentId = new SelectList(_db.Students, "StudentId", "StudentName");
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult AddStudent(Course course, int studentId)
    {
      #nullable enable
      StudentCourse? joinEntity = _db.StudentCourses.FirstOrDefault(join => (join.StudentId == studentId && join.CourseId == course.CourseId));
      #nullable disable
      if (joinEntity == null && studentId != 0)
      {
        _db.StudentCourses.Add(new StudentCourse() { StudentId = studentId, CourseId = course.CourseId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = course.CourseId});
    }
  }
}

Registrar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Registrar.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Registrar/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;

namespace Registrar.Controllers
{
  public class StudentsController : Controller
  {
    private readonly RegistrarContext _db;

    public StudentsController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Students.ToList());
    }

    public ActionResult Details(int id)
    {
      Student thisStudent = _db.Students
      .Include(student => student.JoinEntities)
        .ThenInclude(join => join.Course)
        .FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Student student)
    {
      _db.Students.Add(student);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddCourse(int id)
    {
      Student thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult AddCourse(Student student, int courseId)
    {
      #nullable enable
      StudentCourse? joinEntity = _db.StudentCourses.FirstOrDefault(join => (join.CourseId == courseId && join.StudentId == student.StudentId));
      #nullable disable
      if (joinEntity == null && courseId != 0)
      {
        _db.StudentCourses.Add(new StudentCourse() { CourseId = courseId, StudentId = student.StudentId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = student.StudentId});
    }

    public ActionResult Edit(int id)
    {
      Student thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult Edit(Student student)
    {
      _db.Students.Update(student);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Student thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      return View(thisStudent);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Student thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      _db.Students.Remove(thisStudent);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      StudentCourse joinEntry = _db.StudentCourses.FirstOrDefault(entry => entry.StudentCourseId == joinId);
      _db.StudentCourses.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Registrar/Views/Courses/AddStudent.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course


<h4>Add a student to this course: @Html.DisplayFor(model => model.CourseName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CourseId)

    @Html.Label("Select Student")
    @Html.DropDownList("StudentId")

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Registrar/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course

<h4>Add a new Course</h4>

@using (Html.BeginForm())
{
  @Html.Label("CourseName", "Course Name")
  @Html.TextBoxFor(model => model.CourseName)
  @Html.Label("CourseNumber", "Course Number")
  @Html.TextBoxFor(model => model.CourseNumber)

  <input type="submit" value="add new course" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all Courses", "Index")</p>

Registrar/Views/Courses/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course;

<h2>Are you sure you want to delete this?</h2>

<h2>Course Name: @Html.DisplayFor(model => model.CourseName)</h2>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to course list", "Index")

Registrar/Views/Courses/Details.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models
@model Registrar.Models.Course

<h2>Course Details</h2>

<h3>Course Name: @Html.DisplayFor(model => model.CourseName)</h3>
<h3>Course Number: @Html.DisplayFor(model => model.CourseNumber)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Course does not have any students yet</p>
}
else
{
  <h4>Students enrolled in this course:</h4>
  <ul>
    @foreach(StudentCourse join in Model.JoinEntities)
    {
      <li>Student: @join.Student.StudentName</li>
      @using (Html.BeginForm("DeleteJoin", "Courses"))
      {
        @Html.Hidden("joinId", @join.StudentCourseId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Back to course list", "Index")</p>
<p>@Html.ActionLink("Add a Student", "AddStudent", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Edit Course", "Edit", new { id = Model.CourseId})</p>
<p>@Html.ActionLink("Delete Course", "Delete", new { id = Model.CourseId})</p>

Registrar/Views/Courses/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course

<h2>Edit</h2>

<h4>Edit this course: @Html.DisplayFor(model => model.CourseName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CourseId)

  @Html.Label("CourseName", "Course Name")
  @Html.EditorFor(model => model.CourseName)
  @Html.Label("CourseNumber", "Course Number")
  @Html.EditorFor(model => model.CourseNumber)

  <input type="submit" value="save" />
}

<p>@Html.ActionLink("Back to course list", "Index")</p>

Registrar/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
} 

@using Registrar.Models;

<h1>Courses</h1>

@if (@Model.Count == 0)
{
  <h3>No courses listed yet!</h3>
}

<ul>
  @foreach(Course course in Model)
  {
    <li>@Html.ActionLink($"{course.CourseName}", "Details", new { id = course.CourseId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new course", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Registrar/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to class Registration<h1>

<p>@Html.ActionLink("See all Courses", "Index", "Courses")</p>
<p>@Html.ActionLink("See all Students", "Index", "Students")</p>

Registrar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Registrar</title>
    <link rel="stylesheet" 
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

Registrar/Views/Students/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Student


<h4>Add a Course to this Student: @Html.DisplayFor(model => model.StudentName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StudentId)

    @Html.Label("Select Course")
    @Html.DropDownList("CourseId")

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Registrar/Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Student


<h4>Add a new Student</h4>

@using (Html.BeginForm())
{
  @Html.Label("StudentName", "Student Name")
  @Html.TextBoxFor(model => model.StudentName)
  @Html.Label("DateOfEnrollment", "Date of Enrollment")
  @Html.TextBoxFor(model => model.DateOfEnrollment)

  <input type="submit" value="Add a new Student" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Students", "Index")</p>

Registrar/Views/Students/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Student

<h2>Are you sure you want to remove this Student?</h2>

@Html.DisplayNameFor(model => model.StudentName): @Html.DisplayFor(model => model.StudentName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List of Students", "Index")

Registrar/Views/Students/Details.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models
@model Registrar.Models.Student

<h2>Student Details</h2>
<hr />
<h3>@Html.DisplayFor(model => model.StudentName)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Student does not have any courses yet</p>
}
else
{
  <h4>Courses this student is enrolled in:</h4>
  <ul>
    @foreach(StudentCourse join in Model.JoinEntities)
    {
      <li>Course: @join.Course.CourseName</li>
      @using (Html.BeginForm("DeleteJoin", "Students"))
      {
        @Html.Hidden("joinId", @join.StudentCourseId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Back to List of Students", "Index")</p>
<p>@Html.ActionLink("Edit Student", "Edit")</p>
<p>@Html.ActionLink("Add a Course", "AddCourse", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Remove Student", "Delete", new { id = Model.StudentId})</p>

Registrar/Views/Students/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Student

<h2>Edit</h2>

<h4>Edit this Student Profile: @Html.DisplayFor(model => model.StudentName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StudentId)

  @Html.LabelFor(model => model.StudentName)
  @Html.EditorFor(model => model.StudentName)

  @Html.LabelFor(model => model.DateOfEnrollment)
  @Html.EditorFor(model => model.DateOfEnrollment)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list of Students", "Index")</p>

Registrar/Views/Students/Index.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models;

<h1>Students</h1>

@if (@Model.Count == 0)
{
  <h3>No Students have been added yet</h3>
}
else
{
  <ul>
  @foreach (Student student in Model)
  {
   <li>@Html.ActionLink($"{student.StudentName}", "Details", new { id = student.StudentId})</li>
  }
  </ul>
}

<p>@Html.ActionLink("Add a new Student", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>